"""agregar rejection_type a companies

Revision ID: 18160f0f01ab
Revises: 6c08768f98ca
Create Date: 2026-10-05 22:08:48.246918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18160f0f01ab'
down_revision: Union[str, Sequence[str], None] = '6c08768f98ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('rejection_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'rejection_type')
    # ### end Alembic commands ###
