"""agregar auditoria (AuditMixin) a todas las entidades

Revision ID: 3c10f5c69c11
Revises: b96dd13bd4db
Create Date: 2026-09-18 15:35:59.347559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c10f5c69c11'
down_revision: Union[str, Sequence[str], None] = 'b96dd13bd4db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('assignments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assignments', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.add_column('assignments', sa.Column('updated_by_user_id', sa.UUID(), nullable=True))
    op.add_column('assignments', sa.Column('deleted_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'assignments', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'assignments', 'users', ['deleted_by_user_id'], ['id'])
    op.create_foreign_key(None, 'assignments', 'users', ['updated_by_user_id'], ['id'])
    op.add_column('carriers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('carriers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('carriers', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.add_column('carriers', sa.Column('updated_by_user_id', sa.UUID(), nullable=True))
    op.add_column('carriers', sa.Column('deleted_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'carriers', 'users', ['updated_by_user_id'], ['id'])
    op.create_foreign_key(None, 'carriers', 'users', ['deleted_by_user_id'], ['id'])
    op.create_foreign_key(None, 'carriers', 'users', ['created_by_user_id'], ['id'])
    op.add_column('companies', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.add_column('companies', sa.Column('updated_by_user_id', sa.UUID(), nullable=True))
    op.add_column('companies', sa.Column('deleted_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'companies', 'users', ['updated_by_user_id'], ['id'])
    op.create_foreign_key(None, 'companies', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'companies', 'users', ['deleted_by_user_id'], ['id'])
    op.add_column('dispatch_guides', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('dispatch_guides', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.add_column('dispatch_guides', sa.Column('updated_by_user_id', sa.UUID(), nullable=True))
    op.add_column('dispatch_guides', sa.Column('deleted_by_user_id', sa.UUID(), nullable=True))
    op.alter_column('dispatch_guides', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'dispatch_guides', 'users', ['deleted_by_user_id'], ['id'])
    op.create_foreign_key(None, 'dispatch_guides', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'dispatch_guides', 'users', ['updated_by_user_id'], ['id'])
    op.add_column('documents', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('updated_by_user_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('deleted_by_user_id', sa.UUID(), nullable=True))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'documents', 'users', ['updated_by_user_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'users', ['deleted_by_user_id'], ['id'])
    op.add_column('materials', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('materials', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('materials', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.add_column('materials', sa.Column('updated_by_user_id', sa.UUID(), nullable=True))
    op.add_column('materials', sa.Column('deleted_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'materials', 'users', ['updated_by_user_id'], ['id'])
    op.create_foreign_key(None, 'materials', 'users', ['deleted_by_user_id'], ['id'])
    op.create_foreign_key(None, 'materials', 'users', ['created_by_user_id'], ['id'])
    op.add_column('order_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('order_items', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('order_items', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.add_column('order_items', sa.Column('updated_by_user_id', sa.UUID(), nullable=True))
    op.add_column('order_items', sa.Column('deleted_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'users', ['deleted_by_user_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'users', ['updated_by_user_id'], ['id'])
    op.add_column('orders', sa.Column('updated_by_user_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('deleted_by_user_id', sa.UUID(), nullable=True))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'orders', 'users', ['updated_by_user_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['deleted_by_user_id'], ['id'])
    op.drop_column('orders', 'transport_cost')
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('updated_by_user_id', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('deleted_by_user_id', sa.UUID(), nullable=True))
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'payments', 'users', ['updated_by_user_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'users', ['deleted_by_user_id'], ['id'])
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('updated_by_user_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('deleted_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['updated_by_user_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['deleted_by_user_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['created_by_user_id'], ['id'])
    op.add_column('vehicles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('vehicles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vehicles', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.add_column('vehicles', sa.Column('updated_by_user_id', sa.UUID(), nullable=True))
    op.add_column('vehicles', sa.Column('deleted_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'users', ['deleted_by_user_id'], ['id'])
    op.create_foreign_key(None, 'vehicles', 'users', ['updated_by_user_id'], ['id'])
    op.create_foreign_key(None, 'vehicles', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'deleted_by_user_id')
    op.drop_column('vehicles', 'updated_by_user_id')
    op.drop_column('vehicles', 'created_by_user_id')
    op.drop_column('vehicles', 'updated_at')
    op.drop_column('vehicles', 'created_at')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'deleted_by_user_id')
    op.drop_column('users', 'updated_by_user_id')
    op.drop_column('users', 'created_by_user_id')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('payments', 'deleted_by_user_id')
    op.drop_column('payments', 'updated_by_user_id')
    op.drop_column('payments', 'created_by_user_id')
    op.drop_column('payments', 'updated_at')
    op.add_column('orders', sa.Column('transport_cost', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('orders', 'deleted_by_user_id')
    op.drop_column('orders', 'updated_by_user_id')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'deleted_by_user_id')
    op.drop_column('order_items', 'updated_by_user_id')
    op.drop_column('order_items', 'created_by_user_id')
    op.drop_column('order_items', 'updated_at')
    op.drop_column('order_items', 'created_at')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_column('materials', 'deleted_by_user_id')
    op.drop_column('materials', 'updated_by_user_id')
    op.drop_column('materials', 'created_by_user_id')
    op.drop_column('materials', 'updated_at')
    op.drop_column('materials', 'created_at')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('documents', 'deleted_by_user_id')
    op.drop_column('documents', 'updated_by_user_id')
    op.drop_column('documents', 'created_by_user_id')
    op.drop_constraint(None, 'dispatch_guides', type_='foreignkey')
    op.drop_constraint(None, 'dispatch_guides', type_='foreignkey')
    op.drop_constraint(None, 'dispatch_guides', type_='foreignkey')
    op.alter_column('dispatch_guides', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('dispatch_guides', 'deleted_by_user_id')
    op.drop_column('dispatch_guides', 'updated_by_user_id')
    op.drop_column('dispatch_guides', 'created_by_user_id')
    op.drop_column('dispatch_guides', 'updated_at')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'deleted_by_user_id')
    op.drop_column('companies', 'updated_by_user_id')
    op.drop_column('companies', 'created_by_user_id')
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'created_at')
    op.drop_constraint(None, 'carriers', type_='foreignkey')
    op.drop_constraint(None, 'carriers', type_='foreignkey')
    op.drop_constraint(None, 'carriers', type_='foreignkey')
    op.drop_column('carriers', 'deleted_by_user_id')
    op.drop_column('carriers', 'updated_by_user_id')
    op.drop_column('carriers', 'created_by_user_id')
    op.drop_column('carriers', 'updated_at')
    op.drop_column('carriers', 'created_at')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'deleted_by_user_id')
    op.drop_column('assignments', 'updated_by_user_id')
    op.drop_column('assignments', 'created_by_user_id')
    op.drop_column('assignments', 'updated_at')
    op.drop_column('assignments', 'created_at')
    # ### end Alembic commands ###
