"""agregar paquetes a materials, inventory_movements integer, crear inventory router

Revision ID: 6e8be909083f
Revises: 6c41b362f6c0
Create Date: 2026-09-25 10:08:49.103433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8be909083f'
down_revision: Union[str, Sequence[str], None] = '6c41b362f6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('parent_material_id', sa.UUID(), nullable=True))
    op.add_column('materials', sa.Column('units_per_pack', sa.Numeric(precision=10, scale=3), nullable=True))
    op.create_foreign_key(None, 'materials', 'materials', ['parent_material_id'], ['id'])
    op.drop_column('materials', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_column('materials', 'units_per_pack')
    op.drop_column('materials', 'parent_material_id')
    # ### end Alembic commands ###
