"""agregar verificacion de company: verified_at, verified_by, rejection_reason

Revision ID: 74e669cba533
Revises: 9ef99bdab0ed
Create Date: 2026-09-30 16:36:13.921389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e669cba533'
down_revision: Union[str, Sequence[str], None] = '9ef99bdab0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('verified_by_user_id', sa.UUID(), nullable=True))
    op.add_column('companies', sa.Column('rejection_reason', sa.String(), nullable=True))
    op.create_foreign_key(None, 'companies', 'users', ['verified_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'rejection_reason')
    op.drop_column('companies', 'verified_by_user_id')
    op.drop_column('companies', 'verified_at')
    # ### end Alembic commands ###
