"""rediseno de transporte: quitar vencimientos, agregar document_type y document_blacklist

Revision ID: 87d38ea8c234
Revises: be64dd12254f
Create Date: 2026-09-21 16:17:20.604828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d38ea8c234'
down_revision: Union[str, Sequence[str], None] = 'be64dd12254f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_blacklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('document_number', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('deleted_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type', 'document_number', name='uq_blacklist_type_number')
    )
    op.create_index(op.f('ix_document_blacklist_document_number'), 'document_blacklist', ['document_number'], unique=False)
    op.add_column('assignments', sa.Column('validation_status', sa.String(), nullable=False))
    op.add_column('assignments', sa.Column('rejection_reason', sa.String(), nullable=True))
    op.add_column('assignments', sa.Column('background_check_verified', sa.Boolean(), nullable=False))
    op.add_column('assignments', sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assignments', sa.Column('validated_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'assignments', 'users', ['validated_by_user_id'], ['id'])
    op.add_column('carriers', sa.Column('document_type', sa.String(length=10), nullable=False))
    op.drop_column('carriers', 'license_expiration_date')
    op.drop_column('vehicles', 'soat_expiration_date')
    op.drop_column('vehicles', 'technical_inspection_expiration_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('technical_inspection_expiration_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('vehicles', sa.Column('soat_expiration_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('carriers', sa.Column('license_expiration_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('carriers', 'document_type')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'validated_by_user_id')
    op.drop_column('assignments', 'validated_at')
    op.drop_column('assignments', 'background_check_verified')
    op.drop_column('assignments', 'rejection_reason')
    op.drop_column('assignments', 'validation_status')
    op.drop_index(op.f('ix_document_blacklist_document_number'), table_name='document_blacklist')
    op.drop_table('document_blacklist')
    # ### end Alembic commands ###
