"""agregar person_type y datos fiscales a companies

Revision ID: 9ef99bdab0ed
Revises: fb5a75c9954b
Create Date: 2026-09-29 15:59:16.108480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef99bdab0ed'
down_revision: Union[str, Sequence[str], None] = 'fb5a75c9954b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('person_type', sa.String(), nullable=False, server_default='juridica'))
    op.add_column('companies', sa.Column('fiscal_address', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('fiscal_phone', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('fiscal_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'fiscal_email')
    op.drop_column('companies', 'fiscal_phone')
    op.drop_column('companies', 'fiscal_address')
    op.drop_column('companies', 'person_type')
    # ### end Alembic commands ###
