"""agregar display_name a companies

Revision ID: ab203f6cddc3
Revises: a6a313afca98
Create Date: 2026-09-24 12:03:37.922367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab203f6cddc3'
down_revision: Union[str, Sequence[str], None] = 'a6a313afca98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'display_name')
    # ### end Alembic commands ###
