"""agregar client_code a companies

Revision ID: b96dd13bd4db
Revises: 961892fcfa64
Create Date: 2026-09-18 11:29:56.714091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96dd13bd4db'
down_revision: Union[str, Sequence[str], None] = '961892fcfa64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('client_code', sa.String(), nullable=True))

    connection = op.get_bind()
    companies_table = sa.table(
        'companies',
        sa.column('id', sa.dialects.postgresql.UUID),
        sa.column('type', sa.String),
        sa.column('client_code', sa.String),
    )

    for company_type, prefix in [('own', 'HAC'), ('client', 'CLI')]:
        result = connection.execute(
            sa.select(companies_table.c.id)
            .where(companies_table.c.type == company_type)
            .order_by(companies_table.c.id)
        )
        rows = result.fetchall()

        for index, row in enumerate(rows, start=1):
            code = f"{prefix}-{index:04d}"
            connection.execute(
                companies_table.update()
                .where(companies_table.c.id == row.id)
                .values(client_code=code)
            )

    op.alter_column('companies', 'client_code', nullable=False)
    op.create_unique_constraint(None, 'companies', ['client_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'client_code')
    # ### end Alembic commands ###
