"""crear bank_accounts y actualizar payments para proforma

Revision ID: be64dd12254f
Revises: 3c10f5c69c11
Create Date: 2026-09-19 10:53:48.769934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be64dd12254f'
down_revision: Union[str, Sequence[str], None] = '3c10f5c69c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('account_holder_name', sa.String(), nullable=False),
    sa.Column('account_holder_document_type', sa.String(), nullable=False),
    sa.Column('account_holder_document_number', sa.String(), nullable=False),
    sa.Column('agreement_number', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('deleted_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('payments', sa.Column('bank_account_id', sa.UUID(), nullable=False))
    op.add_column('payments', sa.Column('proforma_number', sa.String(), nullable=False))
    op.add_column('payments', sa.Column('pdf_url', sa.String(), nullable=True))
    op.drop_constraint(op.f('payments_bank_reference_key'), 'payments', type_='unique')
    op.create_unique_constraint(None, 'payments', ['proforma_number'])
    op.create_foreign_key(None, 'payments', 'bank_accounts', ['bank_account_id'], ['id'])
    op.drop_column('payments', 'bank_reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('bank_reference', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='unique')
    op.create_unique_constraint(op.f('payments_bank_reference_key'), 'payments', ['bank_reference'], postgresql_nulls_not_distinct=False)
    op.drop_column('payments', 'pdf_url')
    op.drop_column('payments', 'proforma_number')
    op.drop_column('payments', 'bank_account_id')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
