"""add receipt and rejection reason to payments

Revision ID: d2cd0c825bfd
Revises: 18160f0f01ab
Create Date: 2026-10-08 08:23:34.559362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2cd0c825bfd'
down_revision: Union[str, Sequence[str], None] = '18160f0f01ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('receipt_url', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('receipt_uploaded_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('rejection_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'rejection_reason')
    op.drop_column('payments', 'receipt_uploaded_at')
    op.drop_column('payments', 'receipt_url')
    # ### end Alembic commands ###
