"""agregar unit and  approx_weight_kg a materials

Revision ID: e98b153e9819
Revises: 87d38ea8c234
Create Date: 2026-09-23 09:15:24.005392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98b153e9819'
down_revision: Union[str, Sequence[str], None] = '87d38ea8c234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('approx_weight_kg', sa.Numeric(precision=8, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'approx_weight_kg')
    # ### end Alembic commands ###
