"""agregar category a inventory_movements

Revision ID: fb5a75c9954b
Revises: 8919aa1ccd7e
Create Date: 2026-09-28 16:20:10.591504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5a75c9954b'
down_revision: Union[str, Sequence[str], None] = '8919aa1ccd7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movements', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_movements', 'category')
    # ### end Alembic commands ###
